### PR TITLE
Layout

### LINKED ISSUE #24: Create basic html structure for the About us and Contact us pages
**Is your feature request related to a problem? Please describe.**
To start creating the About us and Contact us pages, we first need to create a basic html structure.

**Describe the solution you'd like**
In the blank html files (aboutsus.html and contactus.html), make a simple html structure on which further components can be added.

**Additional context**
This issue must be solved before proceeding into other issues of About Us and Contact Us pages.

### PR DESCRIPTION
**Pull request by anshkarwasra**
**Related Issue**

**Closes #24** 
**Type of Change**

- [X] New Eliments

**Description of Change**
adds structure for aboutus and contactus section

### CODE REVIEW

**Comment by sasmitaditya13** [comment]
Your commits from a different issues are present in this issue please correct it. The commits are nice. Correct your PR and I'll merge.

**Comment by anshkarwasra** [comment]
what corrections are need to done

**Comment by sasmitaditya13** [comment]
this commit(https://github.com/IMGIITRoorkee/Easysell-website/pull/30/commits/66a80358b11d706560bcf6287c4fff5261debe3d) should not be present in this PR.

**Comment by anshkarwasra** [comment]
i have removed that commit

**Comment by Yash-g2310** [comment]
hey @anshkarwasra it seems you have deleted [landing page css](https://github.com/IMGIITRoorkee/Easysell-website/blob/main/resources/css/landingpage.css) in your last commit, please correct it so that we can then merge your code 
for any doubt feel free to ask your doubt at [discord](https://discord.gg/aKaEbaVYKf)

**Comment by sasmitaditya13** [comment]
Already solved

**Pull request closed without merging**
