### PR TITLE
Added animation in testimonial section #17

### LINKED ISSUE #17: Add animation in testimonial section
**Describe the feature**
below video is the intended behavior of the user review in testimonial on hovering

**Place where it is observed***
1. go to landing page
2. scroll down to testimonials 
3. see the video below for further information

**Screenshots**
below is the expected behavior on hovering
https://github.com/user-attachments/assets/a38c9b2d-32cf-4b13-a352-3b8130816feb

**additional context**
other design ideas on hovering is also welcomed !!

### PR DESCRIPTION
**Pull request by Akshat1276**
Closes #17 

Type of Change
Added animation in testimonial section

New Feature

- [X]  New Feature
- [ ]  Bug Fix
- [ ]  Code Refactor
- [ ]  Documentation Update

Implementation Details
Animation effect when hovering over the testimonial section boxes with the help of CSS `scale` and `transition-duration` properties

Demo Video

https://github.com/user-attachments/assets/2495b086-8ed6-4524-8422-5664d5c5c19d

### CODE REVIEW

**Comment by sasmitaditya13** [comment]
Shouldn't the quotes also be animated?

**Comment by Akshat1276** [comment]
I can do that too. But in the video attached in the issue, the quotes were not animated, so I let them be. Should I animate them now or leave it?

**Comment by sasmitaditya13** [comment]
Yeah animate them

**Comment by Akshat1276** [comment]
Made the changes as advised by you.
Thank You

**Comment by sasmitaditya13** [comment]
Thankyou for contributing

**Pull request merged**
